version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dotnetcore"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1okvqvi0kdeb0"
s3_prefix = "dotnetcore"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
